Cleanup: Add colours to the logging

diff --git a/common b/common
--- a/common
+++ b/common
@@ -6,13 +6,30 @@ set -o pipefail
 
 script_name=${0##*/}
 
+RED='\033[0;31m'
+YELLOW='\033[0;33m'
+BLUE='\033[0;34m'
+NO_COLOUR='\033[0m'
+
+info() {
+    echo -e "${BLUE}${script_name}: Info: ${1:-}${NO_COLOUR}"
+}
+
+warn() {
+    echo -e "${YELLOW}${script_name}: Warning: ${1:-}${NO_COLOUR}"
+}
+
+error() {
+    echo -e "${RED}${script_name}: Error: ${1:-}${NO_COLOUR}" >&2
+}
+
 die() {
-    echo -e "${script_name} - Error: ${1:-}" >&2
+    error "${1:-}"
     exit 1
 }
 
 usage() {
-    [[ -z "${1:-}" ]] || echo -e "Error: ${1}\n" >&2
+    [[ -z "${1:-}" ]] || error "${1:-}"
     grep '^#/' $0 | cut -c 4- | sed \
         -e "s/@PROGRAM@/${script_name}/g" >&2
     exit 1;
